### PR TITLE
Add datadir

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by DeMiro5001** [comment]
@ericgaspar , I just realized that you were working on it with me. 
About the password, I thought to create a var $passwordhash and give it the output of `password_hash('password', PASSWORD_DEFAULT)` inside the script, so the password is never saved in clear, but I don't know if it will work in the yuno script. It will require a loop to add all users and add it in the right place.
And about the datadir, I thought about making for every user a combination of his passwordhash and datadir=/home/yunohost.multimedia/$user.

```
$auth_users = array('Username' => 'Password', 'Username2' => 'Password2')
$directories_users = array('Username' => '/home/yunohost.multimedia/Username', 'Username2' => '/home/yunohost.multimedia/Username2');
```

Or give the admin the choice of the datadir in the manifest.

**Comment by ericgaspar** [comment]
> About the password, I thought to create a var $passwordhash and give it the output of `password_hash('password', PASSWORD_DEFAULT)` inside the script, so the password is never saved in clear, but I don't know if it will work in the yuno script.

This is not likely to work... 
edit2: the config.php file is protected -> `chmod 600 "$final_path/config.php"` (we can try to set it to 400).

Edit: As for the user directories, it is maybe a good idea to use `/home/multimedia/$user` path...

**Comment by ericgaspar** [comment]
I am testing the app. It is working OK appart for image preview not showing (jpg)

**Comment by DeMiro5001** [comment]
> > About the password, I thought to create a var $passwordhash and give it the output of `password_hash('password', PASSWORD_DEFAULT)` inside the script, so the password is never saved in clear, but I don't know if it will work in the yuno script.
> 
> This is not likely to work... edit2: the config.php file is protected -> `chmod 600 "$final_path/config.php"` (we can try to set it to 400).
> 
> Edit: As for the user directories, it is maybe a good idea to use `/home/multimedia/$user` path...

I tried to set the permissions to config.php to 400 and the app couldn't save settings so I had to set it to 600

**Pull request closed without merging**
